; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:esp12f]
board = esp12e
platform = espressif8266
framework = arduino
build_flags = 
	-DDMX_CTRL
  -DWEBSOCKET_CTRL
	-DREMOTE_DEBUG
  ;-DENABLE_DEBUG
	;-DPCA9685_ENABLE_DEBUG_OUTPUT
	;-DDEBUG_WEBSOCKETS=Serial.printf
lib_deps = 
	https://github.com/tzapu/WiFiManager@^2.0.0
	nachtravevl/PCA9685-Arduino@^1.2.15
	https://github.com/Links2004/arduinoWebSockets
	me-no-dev/ESPAsyncTCP
	khoih-prog/ESP8266TimerInterrupt
	vshymanskyy/Preferences
	https://github.com/claudeheintz/LXESP8266DMX
	https://github.com/LennartHennigs/ESPTelnet

[env:esp12fOTA]
extends = env:esp12f
upload_protocol = espota
